### ISSUE TITLE
May have problems with submodule

### ISSUE THREAD

**Issue by allenfantasy** [joyeecheung/diary#1]
### Problem

Just found myself stuck with submodule after forking & pulling down the repo.

After changing `config.js` and `.gitmodules`, I've tried the instructions from README:

```
git submodule sync
git submodule init
git submodule update
```

Then some error bumped out:

> Unable to checkout 'b86879f37437385af97c13ec55947e3a8969f45f' in submodule path 'diary'

It seems like git had store the head ref of the [original submodule](https://github.com/joyeecheung/my-tech-diary/tree/b86879f37437385af97c13ec55947e3a8969f45f) and would checkout some point even if `.gitmodules` have been modified.

My `.gitmodules`:

``` gitconfig
[submodule "diary"]
    path = diary
    url = git@github.com:allenfantasy/my-tech-diary.git
```

---
### Solution

I would like to improve this project and write my blog as well, but haven't found a perfect solution ( c the reference )
- Switch the old submodule to the new
- Delete the old submodule & add a new one
### Reference
- http://stackoverflow.com/questions/14404704/how-do-i-replace-a-git-submodule-with-another-repo
- http://stackoverflow.com/questions/1260748/how-do-i-remove-a-git-submodule
- http://stackoverflow.com/questions/913701/changing-remote-repository-for-a-git-submodule

**Comment by joyeecheung** [comment]
Maybe it would be better to just delete the old submodule and add a new one

```
git rm diary
git submodule add git://new/submodule.git diary
```

Let me know if this works.

**Comment by allenfantasy** [comment]
Seems working well. Just being paranoid to found some staging changes would **never** be committed, like `.gitmodules` and `diary`

PS: there's a typo in [README](https://github.com/joyeecheung/diary/blob/master/README.md#build): 

`.gitsubmodules` ==> `.gitmodules`

**Comment by joyeecheung** [comment]
Didn't think it through because I started it as a personal project...and a submodule seems convenient.

Maybe it's better to create another branch if one wants to commit the changes on the submodule, and checkout the updates on the source code from the master branch.
