### ISSUE TITLE
【Solve】Local preview not working :(

### ISSUE THREAD

**Issue by Anthonyeef** [joyeecheung/diary#4]
First I want to thank you for developing this project cause it's exactly what I need :+1: 

One little problem is, when I finish editing the post and want to see from local server by using `gulp server` command, it only show up the first day's diary but not all my diary in project folder.

I don't know weather it's my own problem or it's the code. My command of daily usage is:
- `cd into/the/sub/module/folder`
- `git pull`
- `cd ..`
- `gulp build`
- `gulp server`

Then I can't see the everyday post inside my submodule folder, but only the first day's post. And after I enter: `gulp deploy` , I can see everything is fine on the internet. Is it my mistake of these command or it's the code's issue?

Though it's not a big problem for daily usage, but I still wigh I could see the local preview before I push to the GitHub...

**Comment by joyeecheung** [comment]
Run `gulp build-debug`, then open `/dist/index.html` and search for `data-last-date` and `data-first-date`, see if they match the latest and oldest diaries of yours. If they are, it should be the problem of your browser cache. If they are not, please let me know.

**Comment by Anthonyeef** [comment]
Hi,

It's working now. I just run `gulp server` and it works fine. I believe there should be no problem within the code and should be the some problem with my browser's cache like you said. 多謝 :)

**Comment by joyeecheung** [comment]
If you need live preview, remember to disable the browser cache(in the network panel of the devtools if you are using Chrome).
