### ISSUE TITLE
在build部分遇到问题

### ISSUE THREAD

**Issue by hizoubin** [joyeecheung/diary#6]
你好，我在执行`git submodule add git://new/submodule.git diary`这一步时，执行失败。
```
fatal: Unable to look up new (port 9418) (nodename nor servname provided, or not known)
fatal: clone of 'git://new/submodule.git' into submodule path '/Users/web/Desktop/diary/diary' failed
```
我ping了github.com，并添加到/etc/hosts中依然无法解决。请问你有好办法吗？

**Comment by joyeecheung** [comment]
`git://new/submodule.git` 指的是存放 markdown 的 git repo 的 url，不是一个实际存在的 url。
